---
apiVersion: v1
kind: Secret
metaData:
  name: {{ include "blog-chart.fullname" . }}-secrets
type: Opaque
data:
  DB_HOST: "{{ .Values.postgresConnectionSettings.DB_HOST | b64enc }}"
  DB_NAME: "{{ .Values.postgresConnectionSettings.DB_NAME | b64enc }}"
  DB_USER: "{{ .Values.postgresConnectionSettings.DB_USER | b64enc }}"
  DB_PASSWORD: "{{ .Values.postgresConnectionSettings.DB_PASSWORD | b64enc }}"
  DB_PORT: "{{ .Values.postgresConnectionSettings.DB_PORT | b64enc }}"