version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10101:80"  # Expose the necessary ports
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Provide a password here
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"  # Map container port 5432 to host port 5432

networks:
  postgres-gorm-network:
    driver: bridge